---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: myns
  labels:
    app: dov
    name: dov-deploy
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: dov-deploy
      env: testing-dov-deploy
  template:
    metadata:
      name: dov-po
      namespace: myns
      labels:
        app: dov-deploy
        env: testing-dov-deploy
    spec:
      containers:
        - name: dov-container
          image: yarou/js-dovbear:v.2
          imagePullPolicy: Always
          env: # enviromental variables
            # - name: INSTANCE_NAME
            #   value: dov pod
            - name: INSTANCE_HASH
              valueFrom:
                fieldRef: 
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: dov-cm
          ports:
            - name: web-port
              containerPort: 5050
            - name: metrics-port
              containerPort: 5100
          livenessProbe:
            httpGet:
              path: /healthz
              port: web-port
            periodSeconds: 30
            initialDelaySeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns
  labels:
    app: dov-deploy
    env: testing-dov-deploy
spec:
  type: ClusterIP
  selector:
      app: dov-deploy
      env: testing-dov-deploy
  ports:
    - name: svc-web-port
      port: 5500
      targetPort: web-port
    - name: svc-metrics-port
      port: 5010
      targetPort: metrics-port