---
apiVersion: v1
kind: Pod
metadata:
  name: dov-po
  namespace: myns
  labels:
    app: dov
    env: testing
spec:
  containers:
    - name: dov-container
      image: yarou/js-dovbear:v.2
      imagePullPolicy: Always
      env: # enviromental variables
        - name: INSTANCE_NAME
          value: dov pod
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef: 
              fieldPath: metadata.labels['env']
      ports:
        - name: web-port
          containerPort: 5050
        - name: metrics-port
          containerPort: 5100
      livenessProbe:
        httpGet:
          path: /healthz
          port: web-port
        periodSeconds: 30
        initialDelaySeconds: 5